# Generated by Django 6.0.2 on 2026-03-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_address_order_delivery_time_order_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='megapixels',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мегапиксели'),
        ),
        migrations.AddField(
            model_name='product',
            name='sensor_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип матрицы'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_resolution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Разрешение видео'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вес'),
        ),
    ]
