# Generated by Django 6.0.2 on 2026-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_megapixels_product_sensor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tech_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Технические характеристики'),
        ),
    ]
