# Generated by Django 6.0.2 on 2026-03-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_tech_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
                ('label', models.CharField(max_length=100, verbose_name='Название поля')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Техническое поле',
                'verbose_name_plural': 'Технические поля',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='tech_fields',
        ),
        migrations.AddField(
            model_name='category',
            name='tech_fields',
            field=models.ManyToManyField(blank=True, to='shop.techfield', verbose_name='Технические характеристики'),
        ),
    ]
