# Generated by Django 6.0.2 on 2026-03-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_techfield_remove_category_tech_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='battery_life',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время работы (ч)'),
        ),
        migrations.AddField(
            model_name='product',
            name='connection',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подключение'),
        ),
        migrations.AddField(
            model_name='product',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Частотный диапазон'),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность (Вт)'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['created_at'],
            },
        ),
    ]
