# Generated by Django 6.0.2 on 2026-03-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_image_product_battery_life_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTechValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_values', to='shop.product', verbose_name='Товар')),
                ('tech_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.techfield', verbose_name='Техническое поле')),
            ],
            options={
                'verbose_name': 'Значение тех. поля товара',
                'verbose_name_plural': 'Значения тех. полей товаров',
                'unique_together': {('product', 'tech_field')},
            },
        ),
    ]
