# Generated by Django 6.0.2 on 2026-05-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_user_address_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('placed', 'Placed'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='cart', max_length=20),
        ),
    ]
